spring:
  jpa:
    database-platform:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
  rabbitmq:
    host: rabbitmq
    port: 5672
    virtual-host: mini_autorizador_host
    username: miniautorizador
    password: pass123

rabbitmq:
  queue-name: transaction_queue
  exchange-name: transaction_exchange
  routing-key-name: transaction_routing_key